import type {AppProps} from 'next/app'
import Head from "next/head";
import '@/styles/globals.css'

export default function App({Component, pageProps}: AppProps) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <div className="layout">
                <header className="p-4 bg-gray-200">Header</header>
                <main>
                    <Component {...pageProps} />
                </main>
                <footer className="p-4 bg-gray-200">Footer</footer>
            </div>
        </>
    );
}
